### ISSUE TITLE
👍

### ISSUE THREAD

**Issue by Sebbyastian** [loathingKernel/KnR2E#1]
This looks pretty good, but I wonder what you'd think about including ??' testcase, since you know ??' shouldn't change the way character constants render, otherwise you might erroneously strip from something like '??'/*this is not a comment*/', for example. I think your code should handle this already. Just thought to add something like this to the test case.

I hope you had a pleasant holiday season.

**Comment by loathingKernel** [comment]
Good idea, thanks for the suggestion.

It was good enough, I hope you did too.
